### PR TITLE
Initial design for #1

### PR DESCRIPTION
**Pull request by denis-sharypin**
offline messages

## Initial design for [Idea#1](https://github.com/status-im/ideas/issues/1)

My thoughts on the offline messaging. I created a basic flow for a fresh user who wants to send a message to an offline friend. This flow is tied to the onboarding flow because we have to describe how our app works for a new user.

I see it like this: we have blue screens with helpful information and we show those screens when the user faces new behavior/concept/UX etc. So in our case when a user tries to send a message to an offline user, I assume we have to tell a user that we are p2p and she has to pay SNT. Also, we should give a quick introduction to SNT. If SNT was already introduced to a user (in different flows) we will skip this screen.

On 8 and 9 you can see how wnode settings look in the user profile.

My questions: what is in the scope for this MVP from all stuff that I prepared?

### CODE REVIEW

**Comment by oskarth** [comment]
Good start!

1. I like the copy/intention in screen 3 and 4. However, I'm a bit hesitant tying screen 2 and 3 together, even if I see reasoning (just in time). What happens if person B is online, then A sends message and they go offline? If we haven't done 3/4 flow this could lead to lost messages and would break user expectations. Can we get this into onboarding somehow (separate swarm)? Maybe with option to "remind me later" (a la Apple setup, 'want to enable location services').

2. Screen 5: Price for what? Per message? I think this is the wrong resolution but not sure what the right one is. You pay for amount of work, so to start with this could be number of messages I guess? Like pay for 1000 messages and top up. But ideally it should be as little to think about from end user POV as possible. See http://nakamotoinstitute.org/static/docs/micropayments-and-mental-transaction-costs.pdf for relevant literature on the problem with micropayments.

3. I like 8 and 9. How will rating and price work though? Relative to what? This is a lot of things to build up.

4. MVP: I think as an MVP we can do 8 with 9 showing just a single Status node w/o reputation and possibly quick text about how more is to come. As an MVP we'll hide this feature behind a flag and SNT payment will not be integrated yet: this will come in future iterations.

5. Intro to SNT: agree, but this might be part of onboarding. Where are we at with this? Would be useful to sync with this (to be?) swarm so we can see where work lands.

**Comment by naghdy** [comment]
- The flow between [2] and [3] will be jarring for a user.
- The subtext under [6] that says "Sent for 1 SNT" is in the right direction, where we provide transparency, but don't get in the way of what a user is expecting
- Slides [8] and [9] look good for the power user who wants to control their offline network nodes. 
- Agree that for an MVP, having a single node with 'more coming soon' is sufficient .

**Comment by sla-shi** [comment]
Agree with the above from @oskarth and @naghdy - the offline messaging settings and preferences should be already sorted out during onboarding #24, before the first chat session occurred.

In the future iterations the list of wnodes as well as every other list in the app should be managed with a more common approach similar to Token Registry #18 - the idea is TBC.

**Comment by denis-sharypin** [comment]
Thanks for comments guys,
@naghdy , @oskarth , @sla-shi 

Let's move a discussion on onboarding here https://github.com/status-im/ideas/issues/24
Also, we need where to discuss and keep economic models of using SNT (are we giving a free credit to a new user, are selling them as a pack or subscription and so on)

Particularly for this topic, I'm going to prepare screens 8 and 9 with reduced number of features as Oscar meant in his comment

**Comment by denis-sharypin** [comment]
@oskarth  I prepared UI in zepplin for MVP
https://zpl.io/V1MOwZZ

**Comment by oskarth** [comment]
Thanks @denis-sharypin

**Comment by oskarth** [comment]
@denis-sharypin What do you imagine a user doing at that screen? Does it visually represent whether you are connected to this node or not? Can you toggle if you are connected?

**Comment by naghdy** [comment]
Zeplin is asking for a password. I can't find it in Lastpass @denis-sharypin

**Comment by oskarth** [comment]
So I just realized this, but looking at the MVP description:

> Goal Date: 2017-11-24
>
> Description: Run a wnode from the command line; let A send message to B who is
offline, and then A goes offline again. When B comes online it should call wnode
which should reply with some payload that contains A's message. This payload
should be visible in A-B's chat. The wnode can be hardcoded.

We don't need the design to be implement for this as the wnode is hardcoded, and that would make us less late for the goal date.

I suggest we include this in version 1 once the concept has been proven. Version 1 scope and capabilities is still TBD but something like:

> Ability to toggle between different wnodes. The wnodes identifiers are hardcoded in the app.

This would then provide a use case for your MVP design and be a first step towards making it a market place.

@denis-sharypin @naghdy How does this sound to you?

**Comment by denis-sharypin** [comment]
@oskarth agree on that

**Comment by oskarth** [comment]
Closing PR since swarm is done.

**Pull request closed without merging**
