### PR TITLE
#158/#212 Ideas should be 3 digits

### LINKED ISSUE #158: Ideas should be three digits
Currently idea numbers are in 1..3 digits. Ensure they are always in three digits, including filenames, README, links etc.

Example: 1-offline-inboxing => 001-offline-inboxing

### PR DESCRIPTION
**Pull request by alexkohler**
Didn't appear to be too many broken links (I attempted to verify via regular expression), let me know if you see any I missed. Fixes #158 and #212 .

### CODE REVIEW

**Comment by oskarth** [comment]
Thanks for the contribution @alexkohler! Looks good to me. Does the `sort: 'id'` definitely work? I had some issues with jekyll not wanting to start when this was enabled IIRC.

Assuming it does, please resolve conflicts and we can go ahead and merge :)

**Comment by alexkohler** [comment]
@oskarth - Everything seems to be running fine locally (this was after merging master):
screen shot 2018-05-01 at 7 41 00 am

**Comment by oskarth** [comment]
Sorry for the delay, thank you so much for the PR! Merging

**Comment by alexkohler** [comment]
@oskarth - No problem! Thanks :smiley:

**Pull request merged**
