### PR TITLE
KISS iteration update: - old in progress -> limbo; old limbo -> aborted

### PR DESCRIPTION
**Pull request by oskarth**
As discussed earlier, we mark all swarms as in limbo per default each iteration, as well as old limbo to aborted. This is the default action, see https://github.com/status-im/ideas/blob/master/MANUAL.md#swarm-lifecycle

Most of these are probably still in progress, but it'd be good to get swarm lead confirmation. This is also a good opportunity to check that idea is up to date w.r.t. contributors and iterations (future and copy-paste town hall, e.g.) etc.

To confirm idea is still in progress and that idea is up to date, just reply "swarm XXX is still in progress", with optional link to PR if adjustments are needed.

In Progress -> Limbo:
- [x] 120-swarm-process
- [x] 121-swarm-compensation
- [x] 92-disc-v5-research
- [x] 87-new-protocol
- [x] 83-energy-efficient
- [x] 80-onboarding
- [x] 68-core-metrics
- [x] 63-refactor-geth-packages
- [x] 58-mainnet
- [x] 34-react-native-qt
- [x] 140-sob-improve-onboarding
- [x] 122-sob-metrics

Limbo -> Aborted:
- [x] 76-smooth-ui
- [ ] 71-low-traffic

---

- [ ] TODO: for swarms real limbo/aborted, update ideas themselves, not just README, also commitment registry

### CODE REVIEW

**Comment by oskarth** [comment]
120 still in progress, https://github.com/status-im/ideas/pull/156/files

**Comment by arash009** [comment]
122 still in progress, https://github.com/status-im/ideas/blob/master/ideas/122-sob-metrics.md

**Comment by chadyj** [comment]
swarm 68-core-metrics is still in progress

**Comment by adambabik** [comment]
In progress:
- `92-disc-v5-research` 
- `63-refactor-geth-packages`
- `58-mainnet`

**Comment by martinklepsch** [comment]
In progress:
- `140-sob-improve-onboarding`
- `121-swarm-compensation`

**Comment by MaxRis** [comment]
Swarm 34-react-native-qt is still in progress. [PR with update](https://github.com/status-im/ideas/pull/162)

**Comment by JekaMas** [comment]
@oskarth It's not clear how to close a swarm?

**Comment by andmironov** [comment]
swarm 80-onboarding is still in progress

**Comment by yenda** [comment]
In progress:

 87-new-protocol

Might have reached all goals at the end of iteration 1 instead of iteration 2

**Comment by oskarth** [comment]
@JekaMas Sorry just saw this now, PR to mark as aborted and completed, and ideally with post-mortem notes. See e.g. idea 1 for one completed example, 64 for aborted one. https://github.com/status-im/ideas/blob/master/MANUAL.md#managing-and-communicating-lifecycle-of-a-swarm-properly

**Comment by oskarth** [comment]
Note to self: consider doing this a different way that requires less coordination, e.g. by just auto marking as limbo since PRs likely contain updates (town hall)

**Pull request merged**
