### PR TITLE
Add extensions #101

### PR DESCRIPTION
**Pull request by jeluard**

### CODE REVIEW

**Comment by martinklepsch** [comment]
I might be interested in being an evaluator for this, ensuring that whatever is build provides utility to the OpenBounty platform.

**Comment by oskarth** [comment]
Requesting review from PM and UX

**Comment by oskarth** [comment]
Merging this since it is a draft.

**Comment by oskarth** [comment]
@jeluard would you mind adding this to idea registry? then we can merge it since it is a draft.

**Comment by jeluard** [comment]
@oskarth Done!

**Comment by oskarth** [comment]
Cheers! Merging

**Pull request merged**
