### PR TITLE
Add lead contributor to idea registry #214

### PR DESCRIPTION
**Pull request by debragail**
*I dont know what add misising data is for 2. task 

Added the column for contributor 
Added column title as Contributor

### CODE REVIEW

**Comment by oskarth** [comment]
Thanks for you contribution @debragail!

Missing data are all the ideas under https://ideas.status.im/all that don't have a lead contributor in their yaml. If you run `bundle exec jekyll serve` this should be visible, and then data is listed as Lead contributor in the idea file.

For example: https://raw.githubusercontent.com/status-im/ideas/master/ideas/58-mainnet.md doesn't have a `lead-contributor` field in yaml, but you can see further down it should be adambabik. This one does have it though: https://raw.githubusercontent.com/status-im/ideas/master/ideas/101-extensions.md

**Comment by oskarth** [comment]
Essentially it's a simple way of knowing who the contact person is for that particular swarm, similar to 'Author field' at http://eips.ethereum.org/all

**Comment by debragail** [comment]
what is different between: ‘contributor’ and ‘lead-contributor’?

**Comment by oskarth** [comment]
@debragail contributors is a list of all the people who committed to the swarm, 'lead-contributor' is the swarm lead, the person responsible for end to end execution of the swarm. The latter is always one person. See https://github.com/status-im/ideas/blob/master/MANUAL.md for more

**Comment by oskarth** [comment]
@debragail Ping on this one

**Comment by debragail** [comment]
I ask because I was going to create lead-contributor and wasn’t sure if it should be a type of contributor structurally

**Comment by debragail** [comment]
I see now.  I fixed it.

**Comment by debragail** [comment]
Following up on this

**Comment by oskarth** [comment]
Hm, I still don't see any missing data having been added? https://github.com/status-im/ideas/pull/221/files I added this separately in another PR, but not for all ideas I believe

**Comment by oskarth** [comment]
I'll go ahead and merge this one as partial solution, it should show us which data is missing more precisely

**Comment by debragail** [comment]
define more precisely

**Comment by debragail** [comment]
this still shows up on the openbounty.status.im

If you could be explicit on what the other data missing is.

**Pull request merged**
