### PR TITLE
Responsive layout - Ideas Table / People Table

### LINKED ISSUE #226: Ideas UI not formatted for mobile browser
in Safari on iOS the menu bar doesn’t size and the table doesn’t format for mobile.

This needs to be designed for mobile and made responsive.

### PR DESCRIPTION
**Pull request by CS76**
Ideas table and people table will now be responsive across small screens
Fixes #226

### CODE REVIEW

**Comment by LaloGarza** [comment]
Thanks for joining! Would love to learn more about your journey into Status Open bounty, mind sending me a DM when you get a chance on https://chat.status.im ! I'm Lalo on there.

**Comment by oskarth** [comment]
Thanks for the PR @CS76! Could you please resolve conflicts?

**Comment by CS76** [comment]
Merged. Thanks 👍

**Comment by oskarth** [comment]
Thanks for your contribution @CS76!

**Pull request merged**
