### PR TITLE
134 seamless login is in progress

### PR DESCRIPTION
**Pull request by oskarth**
PR version of https://github.com/status-im/ideas/commit/a2b3608711ac1cfa4e91f1c04c7a4add85d77967

Draft idea: https://github.com/status-im/ideas/blob/11f8057a4d5aeddc4df6cd8fa18977b589ff2afb/ideas/134-seamless-login.md
See https://github.com/status-im/ideas/pull/164

### CODE REVIEW

**Comment by oskarth** [comment]
I'm not personally convinced:

> Since authentication preference is personal, there will be security/login settings so that a user can customize their desired level of control.

Holds. Users trust us to keep their messages and funds safe, so we should make sure we provide secure defaults. In our case this is further complicated by the fact that messaging and wallet functionality are intricately connected.

Few questions get conversation started:

1) Why was this password required in this way in the first place?

2) How does out threat model change as a consequence of, say, not requiring login?

Additionally it'd be useful to get a few more people who have knowledge of this flow and key structure/authentication mechanisms in general. Requested review from some people.

**Comment by adambabik** [comment]
Agree with both points.

What does sign in process in the app mean now? It only verifies if the person opening the app is authorized or it also decrypts some files, loads some keys etc?

Do we have a clear understanding when the user is logged out? Is it triggered by us after the app goes background or time-based? Actually, I have two-day-old nightly running in the background for one day and I opened it this morning and it did not log me out. The other day though, I remember I needed to put the password quite often.

+1 for integrating with Touch ID and Face ID. I believe it can improve the experience a lot and allow to have a stronger password which would not need to be typed every time. The current experience encourages to define a weak password.

There is one edge case. I believe we should protect "Backup your Seed Phrase" screen with the password even if we decide to go with easier Sign In settings. Unauthorized access to this screen is as much dangerous as sending a transaction (or even more).

**Comment by pilu** [comment]
I also think that we should require a minimum level of security so that a user can't do anything wrong. So giving too many preferences can be dangerous. 

Though I agree that having an easier way to log in would be beneficial for the user experience, and I think this is a very interesting Idea. 

As we already said we should review when and why users are log out, and when the password is used. 

For sure in the current version, we use the password for the generation of the seed that creates the private key, and for encrypting the key store files.
 
I think an important part of this idea is exploring secure enclave and keystore system or alternatives to understand how they work and how to use it in a proper way.

**Comment by alwx** [comment]
Come on,
The first thing we wanted to do is exactly discussing and investigating the possibility of integrating TouchID / FaceID. That's why I don't see any valid reason of reverting the commit and stopping us from doing this work. 
Nobody is going to blindly implement everything we can. We think of security and we're not going to ruin everything we already created. Our first iteraction is dedicated for exploration of possibilities (and not only technical), and we were discussing some of these security concerns during the first kick-off.

> Why was a password required in this way in the first place?
Because it's the obvious and the easiest way of authentication :)

**Comment by oskarth** [comment]
> From a users perspective, the user will not repeatedly be logged out when using Status. This will be the default behavior. Since authentication preference is personal, there will be security/login settings so that a user can customize their desired level of control. For example, a user can specify never to be logged out, or choose to log in every time.

From the product description. This seems to go beyond just changing password to using TouchID/FaceID. Am I missing something @alwx?

**Pull request closed without merging**
