### PR TITLE
marked idea 170 as in progress

### PR DESCRIPTION
**Pull request by goranjovic**
marked idea 170 as in progress

### CODE REVIEW

**Comment by chadyj** [comment]
Can you also please update the status here https://github.com/status-im/ideas/blob/master/ideas/170-wallet-improvements.md and the commitment registry on README.md?

**Comment by chadyj** [comment]
I took a look at the idea but doesn't seem the MVP and iterations were updated after the kick off? It still has an MVP with a due date of yesterday.

**Comment by oskarth** [comment]
@goranjovic as of this weekend we now have a dynamic index that updates idea, commitment registry etc from the idea itself. Would you mind adding YAML frontmatter to the idea, similar to what was done here: https://github.com/status-im/ideas/commit/8d5673e214cbe15b8eeacc001978f2181afe5b4d#diff-ac48ae2b05db150b4eaad2ecfd2c232f - then I think we can unstage README and merge this

**Comment by goranjovic** [comment]
@oskarth @chadyj updated

**Pull request merged**
